/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The therapeutic area / event-type query this timeline covers.
 */
export type Query = string;
/**
 * Human-readable date/period, no more precise than the source data supports.
 */
export type DisplayDate = string;
/**
 * Calendar year, for chronological grouping.
 */
export type Year = number;
/**
 * One of 'Q1'..'Q4' for a specific quarter, 'H1'/'H2' when the source only supports half-year precision, or '' when only a bare year is known.
 */
export type Quarter = string;
export type Company = string;
export type DrugName = string;
export type EventType = string;
export type Indication = string;
/**
 * NCT id or SEC AccessionNumber this event is grounded in.
 */
export type Source = string;
/**
 * 'trial' or 'sec'.
 */
export type SourceType = string;
/**
 * Chronologically sorted, earliest first.
 */
export type Events = CatalystEvent[];

/**
 * Final output: a chronologically sorted catalyst timeline for a query.
 */
export interface CatalystTimeline {
  query: Query;
  events: Events;
}
/**
 * One chronologically-placed catalyst event for the frontend timeline.
 * display_date/year/quarter are computed deterministically from the
 * LLM-cited raw_date by _parse_catalyst_date -- never LLM output.
 */
export interface CatalystEvent {
  display_date: DisplayDate;
  year: Year;
  quarter: Quarter;
  company: Company;
  drug_name: DrugName;
  event_type: EventType;
  indication: Indication;
  source: Source;
  source_type: SourceType;
}
