/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The therapeutic area/indication this landscape covers, copied from the user's request.
 */
export type TherapeuticArea = string;
/**
 * The fixed column headers, in display order: Preclinical, Phase 1, Phase 2, Phase 3, Approved.
 */
export type Phases = string[];
/**
 * A canonical, clinical-grade mechanism of action or molecular target class, e.g. 'PD-1 / PD-L1 Checkpoint Inhibitor', 'EGFR Inhibitor', 'KRAS G12C Inhibitor'. Standard pharmacological classification of a named, real drug IS permitted here even when the retrieved snippet doesn't spell out the mechanism verbatim -- see LANDSCAPE_SYSTEM's classification-vs-study-facts distinction. Use the literal string 'Other / Unspecified Mechanism' only for a genuinely undisclosed investigational code with no published target anywhere in general medical literature.
 */
export type Mechanism = string;
/**
 * One of: Preclinical, Phase 1, Phase 2, Phase 3, Approved -- must match one of the fixed column names given in the prompt exactly.
 */
export type Phase = string;
/**
 * Drug name as it appears in the source record -- generic or brand name, copied exactly, never invented.
 */
export type Name = string;
/**
 * The sponsor/company developing or marketing this drug for this indication, taken from the source record (LeadSponsorName for a trial, SponsorName for an FDA record). Use 'Unknown sponsor' only if genuinely not stated anywhere in the evidence.
 */
export type Sponsor = string;
/**
 * Where this entry's phase placement comes from: an NCT id (e.g. 'NCT01234567') for trial-derived placement, an FDA application number (e.g. 'BLA125514') for FDA-derived Approved placement, or a PMCID (e.g. 'PMC12345678') for a PubMed-derived Preclinical placement. Copied exactly from the record being cited -- never invented.
 */
export type Source = string;
/**
 * Every drug from the retrieved evidence whose most advanced stage for this indication is this phase. Empty list if none -- an empty list is the correct, expected representation of 'nothing at this phase for this mechanism,' not something to omit.
 */
export type Drugs = DrugEntry[];
/**
 * Exactly one PhaseCell per fixed phase column, in the SAME order given in the prompt (Preclinical, Phase 1, Phase 2, Phase 3, Approved) -- always all 5, even when empty.
 */
export type Cells = PhaseCell[];
/**
 * One row per distinct mechanism/target genuinely found in the retrieved evidence, most-populated rows first.
 */
export type Rows = MechanismRow[];

/**
 * Final output: a therapeutic area's competitive landscape matrix.
 */
export interface LandscapeMatrix {
  therapeutic_area: TherapeuticArea;
  phases: Phases;
  rows: Rows;
}
/**
 * One row of the landscape matrix -- a single mechanism/target.
 */
export interface MechanismRow {
  mechanism: Mechanism;
  cells: Cells;
}
/**
 * One column's contents within one mechanism row.
 */
export interface PhaseCell {
  phase: Phase;
  drugs?: Drugs;
}
/**
 * One drug placed in one phase cell of the landscape matrix.
 */
export interface DrugEntry {
  name: Name;
  sponsor: Sponsor;
  source: Source;
}
