/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The high-level analytical answer to the user's question. Every factual claim must cite its NCT id in brackets, e.g. 'targets PD-1 [NCT01234567]'.
 */
export type NarrativeSummary = string;
/**
 * The trial's NCT identifier, e.g. NCT06712888. Must be copied exactly from a retrieved record — never invented.
 */
export type NctId = string;
/**
 * Lead sponsor organisation running the trial.
 */
export type Sponsor = string;
/**
 * Trial phase as a display string, e.g. 'Phase 3' or 'Phase 2/Phase 3' when the trial spans both.
 */
export type Phase = string;
/**
 * The specific intervention names being tested, taken from the record's structured `interventions` field. Prefer therapeutic agents (drugs/biologics) over assessment procedures such as CT or biospecimen collection.
 */
export type Interventions = string[];
/**
 * The primary condition(s) studied -- OVERWRITTEN deterministically from the trial record's own conditions field after extraction; whatever you write here is replaced.
 */
export type Indication = string;
/**
 * Trial recruitment status -- OVERWRITTEN deterministically from the trial record after extraction; whatever you write here is replaced.
 */
export type Status = string;
/**
 * ONE analyst-grade line in EXACTLY this shape: '<Setting/population>: <regimen> vs <comparator> — <the notable point>.' Example: 'First-line R/M HNSCC: cetuximab + pembrolizumab + chemo vs pembrolizumab + chemo — randomized Phase 3.' Another: 'PD-L1+ NSCLC post-progression: trastuzumab deruxtecan (HER2 ADC) + pembrolizumab vs platinum doublet — first ADC-IO pairing in this setting per the record.' FORBIDDEN openings (auto-fail): 'This trial', 'This study', 'This is a', anything containing 'evaluate the safety and efficacy'. Name the mechanism when the text states it. Use ONLY the retrieved text; an unsupported claim is worse than a gap.
 */
export type MechanismOrFindings = string;
/**
 * True ONLY if the retrieved text explicitly names the mechanism of action or biological target of the primary intervention. False if the mechanism/target is not stated, even if other trial design details (like biomarkers) are present.
 */
export type MechanismDescribed = boolean;
/**
 * One of: registry, pdf_literature, fda, pubmed, sec, news.
 */
export type SourceType = string;
/**
 * The cited document's identifier exactly as it appears in the evidence: an NCT id, PMCID, FDA application number, company/ticker, or document title.
 */
export type Reference = string;
/**
 * The excerpt's SourceURL, copied exactly, when present.
 */
export type Url = string | null;
/**
 * Evidence items that informed mechanism_or_findings BEYOND the trial registry record itself: one entry per pool excerpt actually used, copying its PMCID / SourceURL / identifier EXACTLY as it appears in the excerpt. Empty when only the registry record was used. Never invent references -- an uncited claim is better than a fabricated citation.
 */
export type Sources = SourceCitation[];
/**
 * One TrialRow for every distinct trial retrieved from the database. This array backs the frontend data grid.
 */
export type TableData = TrialRow[];
/**
 * TRUE number of trials in the corpus verifiably matching the asked entity, when the query named one. May exceed len(table_data) when the corpus has more matches than the extraction ceiling.
 */
export type TotalMatching = number | null;
/**
 * Number of rows actually shown (len(table_data)); paired with total_matching for the 'Showing X of Y' header.
 */
export type Shown = number | null;
/**
 * Deterministic one-line explanation of the subset rule when total_matching > shown, or of an honest zero-match outcome.
 */
export type CoverageNote = string | null;

/**
 * Final agent output: prose answer + machine-renderable grid.
 */
export interface SmartTableResponse {
  narrative_summary: NarrativeSummary;
  table_data: TableData;
  total_matching?: TotalMatching;
  shown?: Shown;
  coverage_note?: CoverageNote;
}
/**
 * One row of the comparative trials grid.
 */
export interface TrialRow {
  nct_id: NctId;
  sponsor: Sponsor;
  phase: Phase;
  interventions: Interventions;
  indication?: Indication;
  status?: Status;
  mechanism_or_findings: MechanismOrFindings;
  mechanism_described: MechanismDescribed;
  sources?: Sources;
}
/**
 * One clickable provenance link behind a Smart Table row -- the
 * auditability contract: every number an analyst sees should trace to a
 * primary document. The registry citation itself is added
 * DETERMINISTICALLY by extract_trial_node (never trusted to the LLM);
 * the model only cites the auxiliary evidence pools it actually fused.
 */
export interface SourceCitation {
  source_type: SourceType;
  reference: Reference;
  url?: Url;
}
