/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The high-level analytical answer to the user's question. Every factual claim must cite its NCT id in brackets, e.g. 'targets PD-1 [NCT01234567]'.
 */
export type NarrativeSummary = string;
/**
 * The trial's NCT identifier, e.g. NCT06712888. Must be copied exactly from a retrieved record — never invented.
 */
export type NctId = string;
/**
 * Lead sponsor organisation running the trial.
 */
export type Sponsor = string;
/**
 * Trial phase as a display string, e.g. 'Phase 3' or 'Phase 2/Phase 3' when the trial spans both.
 */
export type Phase = string;
/**
 * The specific intervention names being tested, taken from the record's structured `interventions` field. Prefer therapeutic agents (drugs/biologics) over assessment procedures such as CT or biospecimen collection.
 */
export type Interventions = string[];
/**
 * One to two sentences on the mechanism or key finding, taken ONLY from the retrieved trial text. Never supply a mechanism from prior knowledge — an unsupported claim is worse than a gap. If the mechanism is absent, describe whatever trial design or clinical findings are available in the text, and ensure the boolean flag is set to False.
 */
export type MechanismOrFindings = string;
/**
 * True ONLY if the retrieved text explicitly names the mechanism of action or biological target of the primary intervention. False if the mechanism/target is not stated, even if other trial design details (like biomarkers) are present.
 */
export type MechanismDescribed = boolean;
/**
 * One TrialRow for every distinct trial retrieved from the database. This array backs the frontend data grid.
 */
export type TableData = TrialRow[];

/**
 * Final agent output: prose answer + machine-renderable grid.
 */
export interface SmartTableResponse {
  narrative_summary: NarrativeSummary;
  table_data: TableData;
}
/**
 * One row of the comparative trials grid.
 */
export interface TrialRow {
  nct_id: NctId;
  sponsor: Sponsor;
  phase: Phase;
  interventions: Interventions;
  mechanism_or_findings: MechanismOrFindings;
  mechanism_described: MechanismDescribed;
}
